import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css"; // ✅ ensure Toastify styles are imported
import "./globals.css";
import GlobalProvider from "@/components/application/GlobalProvider";
import { Varela_Round } from "next/font/google"; // ✅ built-in font import

// ✅ Configure Google Font (built-in)
const varela = Varela_Round({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${varela.className} antialiased`} // ✅ apply font globally
        suppressHydrationWarning
      >
        <GlobalProvider>
          <ToastContainer />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
